# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.cache/wt [current_project]
set_property parent.project_path C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc709:part0:1.8 [current_project]
set_property ip_output_repo c:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/lut_08.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/lut_07.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/lut_06.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/lut_05.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/lut_04.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/lut_03.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/lut_02.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/lut_01.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/GrayCounterWr.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/GrayCounterData.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/CRC32.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/data_FIFO.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/rxSynchr.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/rxStateMach.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/rxRSstateMach.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/rxFrameState.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/rxFCSCheck.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/lenTypeReg.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/dataCor.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/DAcheck.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/contCharDec.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/rxRS.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/RX.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/tx/rtl/length_FIFO.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/tx/rtl/D_FETCH.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/tx/rtl/data_trans.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/tx/rtl/CRC32_TX.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/rx/rtl/MAC_RX.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/tx/rtl/MAC_TX.v
  C:/Users/sdS/OneDrive/FYP/ip_core/mac/mac.srcs/mac/rtl/MAC.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top MAC -part xc7vx690tffg1761-2


write_checkpoint -force -noxdef MAC.dcp

catch { report_utilization -file MAC_utilization_synth.rpt -pb MAC_utilization_synth.pb }
